# -*- coding: utf-8 -*-

GOLD = {

        'PUM.DE'    : 'PUMA',
        'WDI.DE'    : 'Wirecard',
        'VAR1.DE'   : 'Varta',
        'PAH3.DE'   : 'Porsche Automobil',

        }
DAX = {
        
            '1COV.DE'   : 'Covestro',
            'ADS.DE'    : 'Adidas',            
            'ALV.DE'    : 'Allianz',
            'BAS.DE'    : 'BASF',
            'BAYN.DE'   : 'Bayer',
            'BEI.DE'    : 'Beiersdorf',
            'BMW.DE'    : 'BMW',
            'CON.DE'    : 'Continental',            
            'DAI.DE'    : 'Daimler',
            'DBK.DE'    : 'Deutsche Bank',
            'DB1.DE'    : 'Deutsche Börse',
            'DPW.DE'    : 'Deutsche Post',
            'DTE.DE'    : 'Deutsche Telekom',
            'EOAN.DE'   : 'E.ON',
            'FRE.DE'    : 'Fresenius',
            'FME.DE'    : 'Fresenius Medical',
            'HEI.DE'    : 'Heidelberg Cement',
            'HEN.DE'    : 'Henkel',
            'IFX.DE'    : 'Infineon',
            'LIN.DE'    : 'Linde',
            'LHA.DE'    : 'Lufthansa',
            'MRK.DE'    : 'Merck',
            'MTX.DE'    : 'MTU Aero engines',
            'MUV2.DE'   : 'Münchener',
            'PAH3.DE'   : 'Porsche Automobil',
            'RWE.DE'    : 'RWE',
            'SAP.DE'    : 'SAP',
            'SIE.DE'    : 'Siemens',
            'VNA.DE'    : 'Vonovia',
            'VOW3.DE'   : 'Volkswagen',
            'WDI.DE'    : 'Wirecard',
          }


MDAX = {
            
            'AFX.DE'    : 'Carl Zeiss Meditec',
            'AIR.DE'    : 'Airbus',
            'AOX.DE'    : 'alstria office',
            'ARL.DE'    : 'Aareal Bank',
            'AT1.DE'    : 'Aroundtown',
            'B4B.DE'    : 'Metro',
            'BC8.DE'    : 'Bechtle',
            'BNR.DE'    : 'Brenntag',
            'BOSS.DE'   : 'Hugo Boss',
            'CBK.DE'    : 'Commerzbank',
            'COK.DE'    : 'Cancom',
            'COP.DE'    : 'CompuGroup Medical',
            'DHER.DE'   : 'Delivery Hero', 
            'DLG.DE'    : 'Dialog Semiconductor',
            'DRI.DE'    : '1&1 Drillisch',
            'DUE.DE'    : 'Dürr',
            'DWNI.DE'   : 'Deutsche Wohnen',
            'EVD.DE'    : 'CTS Eventim',
            'EVK.DE'    : 'Evonik Industries',
            'EVT.DE'    : 'Evotec',
            'FIE.DE'    : 'Fielmann',
            'FNTN.DE'   : 'freenet ',
            'FPE3.DE'   : 'Fuchs Petrolub',
            'FRA.DE'    : 'Fraport',
            'G1A.DE'    : 'GEA Group',
            'G24.DE'    : 'Scout24',
            'GLJ.DE'    : 'Grenke',
            'GXI.DE'    : 'Gerresheimer',
            'GYC.DE'    : 'Grand City Properties',
            'HLE.DE'    : 'HELLA GmbH & Co.',
            'HNR1.DE'   : 'Hannover Ruck',
            'HOT.DE'    : 'HOCHTIEF',
            'KBX.DE'    : 'Knorr-Bremse',
            'KGX.DE'    : 'KION GROUP',
            'LEG.DE'    : 'LEG Immobilien',
            'LXS.DE'    : 'LANXESS',
            'MOR.DE'    : 'MorphoSys',
            'NDA.DE'    : 'Aurubis',
            'NEM.DE'    : 'Nemetschek',
            'OSR.DE'    : 'OSRAM Licht',
            'PBB.DE'    : 'Deutsche Pfandbriefbank',
            'PSM.DE'    : 'ProSiebenSat.1 Media',
            'PUM.DE'    : 'PUMA',
            'RAA.DE'    : 'RATIONAL',
            'RHM.DE'    : 'Rheinmetall',
            'RKET.DE'   : 'Rocket Internet',
            'RRTL.DE'   : 'RTL',
            'SDF.DE'    : 'K+S',
            'SHL.DE'    : 'Siemens Healthineers',
            'SOW.DE'    : 'Software',
            'SRT3.DE'   : 'Sartorius',
            'SY1.DE'    : 'Symrise',
            'TEG.DE'    : 'TAG Immobilien',
            'TKA.DE'    : 'thyssenkrupp',
            'O2D.DE'    : 'Telefonica',
            'UN01.DE'   : 'Uniper',
            'UTDI.DE'   : 'United Internet',
            'WAF.DE'    : 'Siltronic',
            'ZAL.DE'    : 'Zalando',
        
        }

SDAX = {
            '8TRA.DE'   : 'Traton',
            'AAD.DE'    : 'Amadeus FiRe',   
            'ADJ.DE'    : 'ADO Propertie',
            'ADL.DE'    : 'ADLER Real Estate',
            'ADV.DE'    : 'ADVA Optical Networking',
            'AIXA.DE'   : 'AIXTRON',
            'BDT.DE'    : 'Bertrandt',
            'BFSA.DE'   : 'Befesa',
            'BVB.DE'    : 'Borussia Dortmund',
            'BYW6.DE'   : 'BayWa',
            'CAP.DE'    : 'Encavis',
            'CCAP.DE'   : 'CORESTATE Capital',
            'CEC.DE'    : 'Lyxor MSCI Eastern Europe',
            'CWC.DE'    : 'CEWE Stiftung',
            'DBAN.DE'   : 'Deutsche Beteiligungs',
            'DEQ.DE'    : 'Deutsche EuroShop',
            'DEZ.DE'    : 'DEUTZ',
            'DIC.DE'    : 'DIC Asset',
            'DMP.DE'    : 'Dermapharm Holding',
            'DRW3.DE'   : 'Dragerwerk',
            'DWS.DE'    : 'DWS Group',
            'EUZ.DE'    : 'Eckert & Ziegler',
            'GBF.DE'    : 'Bilfinger',
            'HAB.DE'    : 'Hamborner REIT',
            'HBH.DE'    : 'Hornbach',
            'HDD.DE'    : 'Heidelberger Druckmaschinen',
            'HHFA.DE'   : 'Hamburger Hafen und Logistik',
            'HNL.DE'    : 'Dr. Honle',
            'HYQ.DE'    : 'Hypoport',
            'IGY.DE'    : 'innogy',
            'INH.DE'    : 'INDUS',
            'INS.DE'    : 'Lyxor Index Fund',
            'ISR.DE'    : 'Isra Vision',
            'JEN.DE'    : 'Jenoptik',
            'JST.DE'    : 'JOST Werke',
            'JUN3.DE'   : 'Jungheinrich',
            'KCO.DE'    : 'Klockner',
            'KRN.DE'    : 'Krones',
            'KWS.DE'    : 'KWS SAAT',
            'LEO.DE'    : 'LEONI',
            'NDX1.DE'   : 'Nordex',
            'NOEJ.DE'   : 'NORMA Group',
            'NWO.DE'    : 'New Work',
            'PAT.DE'    : 'Patrizia',
            'PFV.DE'    : 'Pfeiffer Vacuum',
            'RHK.DE'    : 'RHON-KLINIKUM',
            'RIB.DE'    : 'RIB Software',
            'S92.DE'    : 'SMA Solar Technology',
            'SANT.DE'   : 'S&T',
            'SAE.DE'    : 'Shop Apotheke',
            'SAX.DE'    : 'Stroer SE & Co.',
            'SFQ.DE'    : 'SAF-Holland',
            'SGL.DE'    : 'SGL Carbon',
            'SHA.DE'    : 'Schaeffler',
            'SIX2.DE'   : 'Sixt',
            'SKB.DE'    : 'Koenig & Bauer',
            'STM.DE'    : 'Stabilus',
            'SZG.DE'    : 'Salzgitter',
            'SZU.DE'    : 'Sudzucker',
            'TLG.DE'    : 'TLG Immobilien',
            'TLX.DE'    : 'Talanx',
            'TTK.DE'    : 'TAKKT',
            'VAR1.DE'   : 'Varta',
            'WAC.DE'    : 'Wacker Neuson',
            'WCH.DE'    : 'Wacker Chemie',
            'WSU.DE'    : 'WashTec', 
            'WUW.DE'    : 'Wustenrot & Wurttembergische',
            'ZO1.DE'    : 'zooplus',
        }

GREEN = {

#            '2GB.DE'    : '2G Energy',
#            '93M.DE'    : 'MPH Health Care',
#            'BWQ.DE'    : 'Advanced Blockchain',
#            'BEZ.DE'    : 'Berentzen-GRP',
#            'CE2.DE'    : 'CropEnergies',
#            'CURK.DE'   : 'Curasan',
#            'EIN3.DE'   : 'Einhell',
#            'EXN.DE'    : 'Expedeon',
#            'FYB.DE'    : 'Formycon',
#            'H24.DE'    : 'home24',
#            'H9Y.DE'    : 'HanseYachts',
#            'IC8.DE'    : 'InCity Immobilien',
#            'LOUD.DE'   : 'DEAG Deautsche Entertainment',
#            'M7U.DE'    : 'Nynomic',
#            'MSAG.DE'   : 'MS Industrie',
#            'NC5A.DE'   : 'NorCom Information',
#            'PAL.DE'    : 'Pantafilix',
#            'PNE3.DE'   : 'PNE AG',
#            'SCE.DE'    : 'Schweizer Electronic',
#            'SF3.DE'    : 'STS Group',
#            'SHWK.DE'   : 'SHS VIVEON',
#            'SYT.DE'    : 'Softing',
#            'TMV.DE'    : 'Teamviewer',
#            'TTI.DE'    : 'Tom Tailor',
#            'ULC.DE'    : 'United labels',
#            'VQT.DE'    : 'va-Q-tec',
#            'WEW.DE'    : 'Westwing',

                          
          }


RED = {
            }
        
        
